name: kisan
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  adobe_xd:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  firebase_auth:
  cloud_firestore:
  google_sign_in:
  firebase_core:
  provider:
  shared_preferences:
  country_code_picker:
  image_picker:
  flutter_spinkit:
  connectivity:
  geocoder:
  datetime_picker_formfield:
  google_maps_flutter:
  location:
  firebase_storage:
  get_it:
  ff_navigation_bar:
  file_picker:
  geocoding:
  geolocator:
  flutter_map:
  firebase_database:
  cached_network_image:
  fluttertoast:
  photo_view:
  firebase_messaging:
  flutter_local_notifications:
  map_polyline_draw: ^1.0.4
  permission_handler:
  flutter_phone_direct_caller: ^2.0.0
  flutter_svg:




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:

flutter_icons:
  image_path: "assets/KC.png"
  android: true
  ios: true




# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  generate: true






  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/anlytics.png
    - assets/CS.png
    - assets/earn.png
    - assets/edit.png
    - assets/farmer (2).png
    - assets/farming.jpg
    - assets/fb_logo.png
    - assets/google.png
    - assets/home.png
    - assets/home1.png
    - assets/info.png
    - assets/internat.png
    - assets/KC.png
    - assets/KC logo.png
    - assets/KC1.png
    - assets/kc_logo_d.png
    - assets/locaiton.png
    - assets/logout.png
    - assets/manu.png
    - assets/message.png
    - assets/mini-rotary-tiller.png
    - assets/notification.png
    - assets/phone.png
    - assets/QR.png
    - assets/ram1.png
    - assets/rupees-symbol-png-27187 (1).png
    - assets/rupees-symbol-png-27204.png
    - assets/sent.png
    - assets/senttings.png
    - assets/share.png
    - assets/smart_phone.png
    - assets/star.png
    - assets/SV1.png
    - assets/TC.png
    - assets/TC2.png
    - assets/welcome.png
    - assets/work.png
    - assets/leaf.png

  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
